# Movement IDs -> templates, authentic-name aliases, descriptor heuristics, defaults.
MOVEMENTS = {
    "march": "march", "easy_walk": "walk", "low_jack": "jack", "wrist_circles": "wrist_circles",
    "wrist_rocks": "wrist_rock", "shoulder_cars": "shoulder_circles", "arm_swings": "arm_swings",
    "cat_cow": "cat_cow", "thoracic_rotation": "thoracic_rotation", "hip_circles": "hip_circles",
    "ankle_rocks": "ankle_rock", "leg_swings": "leg_swing",
    "scapular_pull": "scapular_pull", "scapular_pushup": "scapular_pushup",
    "elevated_scapular_pushup": "scapular_pushup_incline",
    "dead_hang": "hang", "foot_assisted_hang": "foot_assisted_hang", "active_hang": "active_hang",
    "assisted_pullup": "assisted_pullup", "eccentric_pullup": "eccentric_pullup", "pullup": "pullup", "chinup": "pullup",
    "inverted_row": "row", "high_inverted_row": "high_row", "feet_elevated_row": "feet_elevated_row",
    "support_hold": "support", "foot_assisted_support": "foot_assisted_support", "assisted_dip": "assisted_dip",
    "eccentric_dip": "eccentric_dip", "parallel_dip": "dip", "straight_bar_support": "straight_bar_support",
    "incline_pushup": "incline_pushup", "pushup": "pushup", "pause_pushup": "pause_pushup",
    "close_pushup": "close_pushup", "pike_pushup": "pike_pushup",
    "squat": "squat", "box_squat": "box_squat", "tempo_squat": "tempo_squat", "pause_squat": "pause_squat",
    "reverse_lunge": "reverse_lunge", "split_squat": "split_squat", "cossack_squat": "cossack",
    "calf_raise": "calf_raise", "glute_bridge": "glute_bridge", "single_leg_bridge": "single_leg_bridge",
    "plank": "plank_forearm", "incline_plank": "incline_plank", "hollow_hold": "hollow_hold",
    "dead_bug": "dead_bug", "bird_dog": "bird_dog", "side_plank": "side_plank",
    "knee_raise": "hanging_knee_raise", "lying_knee_raise": "lying_knee_raise", "lying_leg_raise": "lying_leg_lower",
    "arch_hold": "arch_hold", "tuck_lsit": "tuck_lsit", "candlestick": "candlestick",
    "low_bar_transition": "low_bar_transition", "pullover_lowbar": "pullover_lowbar", "jump_muscleup": "jump_muscleup",
    "chest_to_bar": "chest_to_bar", "band_muscleup": "muscleup", "strict_muscleup": "muscleup",
    "tuck_front_row": "tuck_front_row", "tuck_front_hold": "front_lever_tuck", "advanced_tuck_front": "front_lever_adv",
    "one_leg_front": "front_lever_one_leg", "straddle_front": "front_lever_straddle", "full_front": "front_lever_full",
    "skin_cat_partial": "skin_the_cat", "tuck_back_entry": "back_lever_entry", "tuck_back_hold": "back_lever_tuck",
    "advanced_tuck_back": "back_lever_adv", "one_leg_back": "back_lever_one_leg", "straddle_back": "back_lever_straddle",
    "full_back": "back_lever_full",
    "bent_dragon_negative": "dragon_bent_negative", "one_leg_dragon_negative": "dragon_one_leg_negative",
    "full_dragon_negative": "dragon_negative", "dragon_flag": "dragon_flag",
    "elevated_plank": "incline_plank", "planche_lean": "planche_lean", "frog_stand": "frog_stand",
    "tuck_planche": "tuck_planche", "advanced_tuck_planche": "adv_tuck_planche", "straddle_planche": "straddle_planche",
    "full_planche": "full_planche",
    "forearm_stretch": "forearm_stretch", "lat_stretch": "lat_stretch", "chest_stretch": "chest_stretch",
    "hip_flexor_stretch": "hip_flexor_stretch", "hamstring_stretch": "hamstring_stretch", "quad_stretch": "quad_stretch",
    "calf_stretch": "calf_stretch", "child_pose": "child_pose", "supine_twist": "supine_twist", "slow_breathing": "breathing",
    "adductor_stretch": "cossack_hold", "bear_crawl": "bear_crawl", "deep_squat_hold": "deep_squat_hold",
    "hollow_arch_swing": "hollow_arch_swing", "negative_muscleup": "negative_muscleup",
    "ninety_ninety_hip_stretch": "ninety_ninety_stretch", "ninety_ninety_hip_switch": "ninety_ninety_switch",
    "parallel_bar_walk": "hand_walk", "pseudo_planche_pushup": "pseudo_planche_pushup", "step_up": "step_up",
    "straight_bar_dip": "straight_bar_dip", "wall_pushup": "wall_pushup", "wall_slide": "wall_slide",
    "assisted_pistol_squat": "pistol_assisted", "pistol_squat": "pistol",
    "hanging_leg_raise": "hanging_leg_raise", "toes_to_bar": "toes_to_bar",
}

# Exact English names from the recovered catalog (all 34 distinct names).
ALIASES = {
    "2/3 Muscle Up": "two_thirds_muscleup",
    "Assisted Pull Over": "negative_muscleup",
    "Bar Dips": "straight_bar_dip",
    "Compound Exercise": "standing_mobility",
    "Dips": "dip",
    "Front Lunges": "front_lunge",
    "Front Support": "plank_arm_raise",
    "Full Body Raise": "front_lever_raise",
    "Half Dips": "half_dip",
    "Hang": "hang",
    "Hanging Knee Raise": "hanging_knee_raise",
    "Hanging Leg Raise": "hanging_leg_raise",
    "Inverted Hang": "inverted_hang_lower",
    "Inverted Hang - Attempt": "inverted_hang",
    "Inverted L - Isometric Hold": "hanging_lsit",
    "Inverted Row": "row",
    "Jump To Hang On High Bar": "jump_to_hang",
    "Jump To Hang On High Bar - Push Up": "jump_to_hang",
    "Leg Raise": "support_knee_raise",
    "Muscle Up": "muscleup",
    "Parallel Bars - Hand Walk": "hand_walk",
    "Plank": "plank_forearm",
    "Pull Over": "pullover",
    "Pull Over, Forward Roll": "pullover",
    "Pull Up": "pullup",
    "Push Up": "pushup",
    "Rolling Shoulder Shrugs": "support_shrug",
    "Shoulder Shrugs": "support_shrug",
    "Side Plank": "side_plank",
    "Single Leg Squat": "pistol",
    "Squat": "squat",
    "Squat Jump": "squat_jump",
    "Tucked Back Lever Pull Up": "back_lever_pullup",
    "Windshield Wiper": "windshield_wiper",
}

# Searched against "name + description + set names" (normalized); the earliest match in the text wins,
# ties resolved by list order. Specific phrases come before generic ones.
HEURISTICS = [
    (["hanging shoulder shrugs", "scapular pull"], "scapular_pull"),
    (["kipping swing", "straight body swing", "body swing"], "hollow_arch_swing"),
    (["negative muscle up", "negative muscle-up"], "negative_muscleup"),
    (["2/3 muscle up", "elbows over top of the bar"], "two_thirds_muscleup"),
    (["muscle up", "muscleup"], "muscleup"),
    (["forward roll", "pull over"], "pullover"),
    (["front lever", "full body raise"], "front_lever_raise"),
    (["one third back lever", "1/3 back lever"], "inverted_hang_lower"),
    (["tucked back lever pull up"], "back_lever_pullup"),
    (["back lever", "skin the cat", "german hang", "reverse pull over"], "back_lever_tuck"),
    (["dragon flag"], "dragon_flag"),
    (["planche"], "tuck_planche"),
    (["toes to bar"], "toes_to_bar"),
    (["l-sit hold", "l sit hold", "lsit hold"], "hanging_lsit"),
    (["windshield wiper"], "windshield_wiper"),
    (["knee-hip raise", "knee hip raise"], "knee_hip_raise"),
    (["hanging knee raise", "knees to chest"], "hanging_knee_raise"),
    (["hanging leg raise"], "hanging_leg_raise"),
    (["head banger", "head bangers"], "head_banger"),
    (["negative pull up", "negative pull-up", "jumping negative"], "eccentric_pullup"),
    (["chest to bar"], "chest_to_bar"),
    (["jump to hang", "jump into half pull up", "jump to overhand"], "jump_to_hang"),
    (["pull up", "pull-up", "chin up", "chin-up", "chin ups"], "pullup"),
    (["inverted row", "body row"], "row"),
    (["bar dips", "bar dip"], "straight_bar_dip"),
    (["half dips", "half dip"], "half_dip"),
    (["dips"], "dip"),
    (["hand walk"], "hand_walk"),
    (["shoulder shrugs", "support shrugs"], "support_shrug"),
    (["walking hand plank", "hand plank"], "plank_walk"),
    (["single arm front raise", "front support"], "plank_arm_raise"),
    (["plank up"], "plank_up"),
    (["side plank"], "side_plank"),
    (["plank"], "plank_forearm"),
    (["hand release"], "hand_release_pushup"),
    (["push up", "push-up", "pushup"], "pushup"),
    (["squat jump"], "squat_jump"),
    (["single leg squats one third", "single leg squat one third"], "pistol_partial"),
    (["single leg squat", "pistol"], "pistol"),
    (["jumping lunges", "jumping lunge"], "jumping_lunge"),
    (["back lunges", "reverse lunge"], "reverse_lunge"),
    (["front lunges", "lunges", "lunge"], "front_lunge"),
    (["squat"], "squat"),
    (["knee raise"], "support_knee_raise"),
    (["leg raise"], "hanging_leg_raise"),
    (["crawl"], "bear_crawl"),
    (["bridge"], "glute_bridge"),
    (["hollow"], "hollow_hold"),
    (["stretch"], "hamstring_stretch"),
]

CATEGORY_DEFAULTS = {
    "dynamic_warmup": "standing_mobility", "recovery": "breathing", "mobility": "standing_mobility",
    "activation": "scapular_pull", "fundamental": "squat", "skill_foundation": "hollow_hold",
    "skill": "front_lever_tuck", "advanced_skill": "front_lever_adv", "static_stretch": "hamstring_stretch",
    "static_cooldown": "hamstring_stretch", "conditioning": "bear_crawl", "strength": "squat",
    "skill_drill": "hollow_arch_swing",
}
EQUIPMENT_DEFAULTS = {
    "high_bar": "hang", "low_bar": "row", "parallel_bars": "support", "secure_incline": "incline_plank",
    "wall": "wall_slide", "mat": "hollow_hold", "box": "step_up", "support": "leg_swing",
}
FALLBACK = "standing_mobility"

# Explicit IDs for the shared morning-class skill ladders.
MOVEMENTS.update({name: name for name in ["overhead_line", "kneeling_side_plank", "pike_handstand_hold", "wall_handstand", "handstand_toe_pull", "handstand_balance", "flag_ground_support", "assisted_tuck_flag", "tuck_flag"]})
